In [61]:
## imports
from rich.pretty import pprint

## Import and set configs

In [62]:
from ftse.gin.utils import instantiate
instantiate();

from ftse.data.data_loader import get_datasets

## Load datasets

In [63]:
datasets = get_datasets()

## Print dataset keys

In [64]:
print(list(datasets.keys()))

['Appliances energy prediction Data Set', 'Gas sensor array temperature modulation', 'Household Electric Power Consumption', 'Machinery Fault Diagnosis', 'MetroPT-3 Dataset', 'Predictive Maintenance Of Hydraulics System', 'SKAB - Skoltech Anomaly Benchmark', 'Unleashing the Power of Wearables', 'c3server', 'liu', 'NATOPS', 'Epilepsy', 'ArticularyWordRecognition', 'UWaveGestureLibrary', 'SelfRegulationSCP2', 'Cricket', 'ERing', 'CharacterTrajectories', 'FingerMovements', 'SelfRegulationSCP1', 'BasicMotions', 'AtrialFibrillation', 'HandMovementDirection', 'Handwriting', 'Libras', 'LSST', 'RacketSports', 'SpokenArabicDigits', 'weather', 'illness', 'ett']


## Access dataset element

In [20]:
datasets['Appliances energy prediction Data Set'][0]

Data(data=tensor([[60.0000, 30.0000, 19.8900,  ...,  7.0000, 63.0000,  5.3000],
        [60.0000, 30.0000, 19.8900,  ...,  6.6667, 59.1667,  5.2000],
        [50.0000, 30.0000, 19.8900,  ...,  6.3333, 55.3333,  5.1000],
        ...,
        [50.0000,  0.0000, 20.0000,  ...,  7.8333, 40.0000,  3.9300],
        [60.0000,  0.0000, 20.0000,  ...,  8.0000, 40.0000,  3.9000],
        [60.0000,  0.0000, 20.0000,  ...,  7.5000, 40.0000,  3.7300]],
       dtype=torch.float64), descriptions=['Energy usage of appliance in Wh', 'Energy usage of light fixtures in the house in Wh', 'Temperature in kitchen area in Celsiue', 'Humidity in kitchen area in %', 'Temperature in living room area in Celsius', 'Humidity in living room area in %', 'Temperature in laundry room area', 'Humidity in laundry room area in %', 'Temperature in office room in Celsius', 'Humidity in office room in %', 'Temperature in bathroom in Celsius', 'Humidity in bathroom in %', 'Temperature outside the building (north side) in Cel

In [89]:
import h5py

In [97]:
H5_FILE = '/data/TimeSeriesResearch/datasets/new_time_series_data.h5'

In [98]:
f = h5py.File(H5_FILE, 'r')

In [100]:
f.keys()

<KeysViewHDF5 ['Appliances energy prediction Data Set___No Annotation___0', 'Gas sensor array temperature modulation___No Annotation___0', 'Gas sensor array temperature modulation___No Annotation___1', 'Gas sensor array temperature modulation___No Annotation___10', 'Gas sensor array temperature modulation___No Annotation___11', 'Gas sensor array temperature modulation___No Annotation___12', 'Gas sensor array temperature modulation___No Annotation___2', 'Gas sensor array temperature modulation___No Annotation___3', 'Gas sensor array temperature modulation___No Annotation___4', 'Gas sensor array temperature modulation___No Annotation___5', 'Gas sensor array temperature modulation___No Annotation___6', 'Gas sensor array temperature modulation___No Annotation___7', 'Gas sensor array temperature modulation___No Annotation___8', 'Gas sensor array temperature modulation___No Annotation___9', 'Household Electric Power Consumption___No Annotation___0', 'Machinery Fault Diagnosis___horizontal-mi

In [ ]:
###

# constraints: multivariate and descriptions are present.

# Download .mat files in the jupyter lab env (done)
# Load into notebook, and create a new h5 file in the jupyter lab memory
# Ensure h5 key structure follows : dsname_label_fileidx
# Make sure .attrs['descriptions'] is included
# Validate: run load_h5py_dataset, with h5_file = new_h5_file.h5

In [93]:
f.keys()6

<KeysViewHDF5 ['BCSV___Ball___0', 'BCSV___Ball___1', 'BCSV___Ball___2', 'BCSV___Ball___3', 'BCSV___Ball___4', 'BCSV___Ball___5', 'BCSV___Ball___6', 'BCSV___Ball___7', 'IBCSV___Inner_and_Ball___0', 'IBCSV___Inner_and_Ball___1', 'IBCSV___Inner_and_Ball___2', 'IBCSV___Inner_and_Ball___3', 'IOCSV___Inner_and_Outer___0', 'IOCSV___Inner_and_Outer___1', 'IOCSV___Inner_and_Outer___2', 'IOCSV___Inner_and_Outer___3', 'IOCSV___Inner_and_Outer___4', 'OCSV___Outer_and_Ball___0', 'OCSV___Outer_and_Ball___1', 'OCSV___Outer_and_Ball___2', 'OCSV___Outer_and_Ball___3', 'OCSV___Outer_and_Ball___4', 'OCSV___Outer_and_Ball___5', 'OCSV___Outer_and_Ball___6', 'OCSV___Outer_and_Ball___7', 'OCSV___Outer_and_Ball___8']>

In [17]:
datasets['ett'][0]

Data(data=tensor([[ 5.8270,  2.0090,  1.5990,  0.4620,  4.2030,  1.3400, 30.5310],
        [ 5.6930,  2.0760,  1.4920,  0.4260,  4.1420,  1.3710, 27.7870],
        [ 5.1570,  1.7410,  1.2790,  0.3550,  3.7770,  1.2180, 27.7870],
        [ 5.0900,  1.9420,  1.2790,  0.3910,  3.8070,  1.2790, 25.0440],
        [ 5.3580,  1.9420,  1.4920,  0.4620,  3.8680,  1.2790, 21.9480],
        [ 5.6260,  2.1430,  1.5280,  0.5330,  4.0510,  1.3710, 21.1740],
        [ 7.1670,  2.9470,  2.1320,  0.7820,  5.0260,  1.8580, 22.7920],
        [ 7.4350,  3.2820,  2.3100,  1.0310,  5.0870,  2.2240, 23.1440],
        [ 5.5590,  3.0140,  2.4520,  1.1730,  2.9550,  1.4320, 21.6670],
        [ 4.5550,  2.5450,  1.9190,  0.8170,  2.6800,  1.3710, 17.4460],
        [ 4.9570,  2.5450,  1.9900,  0.8530,  2.9550,  1.4920, 19.9790],
        [ 5.7600,  2.5450,  2.2030,  0.8530,  3.4420,  1.4920, 20.1190],
        [ 4.6890,  2.5450,  1.8120,  0.8530,  2.8330,  1.5230, 19.2050],
        [ 4.6890,  2.6790,  1.7770,  1.24

In [12]:
pprint(datasets['ett'][0].__dict__.keys())

dict_keys(['data', 'descriptions', 'label', 'dataset_name', 'positions'])

In [15]:
# of these, the main ones are data, descriptions, label, dataset_name
pprint(type(datasets['ett'][0].data))
pprint(type(datasets['ett'][0].descriptions))
pprint(type(datasets['ett'][0].label))
pprint(type(datasets['ett'][0].dataset_name))

<class 'torch.Tensor'>

<class 'list'>

<class 'NoneType'>

<class 'str'>

In [47]:
from collections import defaultdict
from ftse.data.Dataset import UnwindowedDataset
from tqdm.auto import tqdm
import os
import h5py
import numpy as np
import pandas as pd
import torch

In [75]:
ROOT_DIRS = [
    '/workspace/research/ftse/ftse/notebooks/'
]

H5_FILE = '/workspace/research/ftse/ftse/notebooks/testing3.h5'

root_dirs=ROOT_DIRS
h5_file=H5_FILE

In [76]:
with h5py.File(h5_file, "w") as h5f:
    for root_dir in root_dirs:
        root_prefix = os.path.basename(os.path.normpath(root_dir))
        print("root_prefix", root_prefix)
        for dataset_folder in tqdm(os.listdir(root_dir), desc=f"Datasets in {root_dir}"):
            #print("dataset_folder", dataset_folder)
            dataset_path = os.path.join(root_dir, dataset_folder)
            if not os.path.isdir(dataset_path):
                #print("skipping", dataset_path)
                continue  # Skip non-directory items
            label_counts = {}

            for csv_file in tqdm(os.listdir(dataset_path), desc=dataset_folder, leave=False):
                if not csv_file.lower().endswith(".csv"):
                    continue

                # Example filename: "file_5_Normal Operation.csv"
                # Extract label: take everything after the second underscore and strip ".csv".
                parts = csv_file.split('_')
                if len(parts) >= 3:
                    label = '_'.join(parts[2:]).replace('.csv', '')
                else:
                    label = "Unknown"

                # Initialize or update the file index counter for this label.
                if label not in label_counts:
                    label_counts[label] = 0
                file_idx = label_counts[label]
                label_counts[label] += 1

                # Read the CSV file.
                csv_path = os.path.join(dataset_path, csv_file)
                df = pd.read_csv(csv_path)
                # Drop unwanted columns.
                cols_to_drop = ['Unnamed: 0', 'time_sec', 'Time', 'Label']
                df = df.drop([col for col in cols_to_drop if col in df.columns], axis=1)
                # Save the column names as metadata.
                column_names = df.columns.tolist()
                data_array = df.to_numpy()
                # Create a flat key in the format:
                # "root_prefix___dataset_folder___label___file_idx"
                key = f"{dataset_folder}___{label}___{file_idx}"
                dset = h5f.create_dataset(key, data=data_array)
                dset.attrs["descriptions"] = list(column_names)

root_prefix notebooks


Datasets in /workspace/research/ftse/ftse/notebooks/:   0%|          | 0/20 [00:00<?, ?it/s]

NCSV: 0it [00:00, ?it/s]

OCSV:   0%|          | 0/9 [00:00<?, ?it/s]

[[-2.20713019e-02 -8.98239550e-03 -4.17898319e-05]
 [-1.07025068e+00 -9.83588730e-03 -8.32209034e-05]
 [-6.20899438e-01 -1.05613553e-02 -1.24823556e-04]
 ...
 [-1.06300209e+00 -8.30315844e-01  1.43189796e+03]
 [-2.46515500e+00 -1.04526166e+00  1.43190055e+03]
 [-2.03342837e+00 -6.12638857e-01  1.43190305e+03]]
OCSV___Outer_and_Ball___0
[[-4.04185677e-01 -7.53755581e-03  9.80253098e+00]
 [-3.43587759e-01 -1.06832827e-02  9.80446899e+00]
 [-8.64553058e-01 -1.06771864e-02  9.80660358e+00]
 ...
 [ 9.74297429e-02  2.45248426e-01  8.13963763e+02]
 [ 5.77970012e-01 -2.51928836e-01  8.13970530e+02]
 [-5.82705680e-01 -1.88240059e-01  8.13977309e+02]]
OCSV___Outer_and_Ball___1
[[ 2.41407713e-01  3.33227190e-03  8.41927304e+00]
 [ 1.10728734e+00 -1.05674517e-02  8.42212725e+00]
 [ 4.35235701e-01  3.78949965e-03  8.42470234e+00]
 ...
 [-7.73016062e-01 -7.05706041e-01  1.42156418e+03]
 [ 6.06259572e-02 -1.23313718e-01  1.42156466e+03]
 [-9.99416955e-01 -1.71974944e-01  1.42156517e+03]]
OCSV___Outer

.ipynb_checkpoints:   0%|          | 0/6 [00:00<?, ?it/s]

IOCSV:   0%|          | 0/5 [00:00<?, ?it/s]

[[-2.17118564e-01  5.16118290e-03 -1.42960595e-04]
 [ 4.93730371e-01  6.96570842e-03 -2.89033190e-04]
 [ 5.95564136e-01  3.27130820e-03 -4.19739280e-04]
 ...
 [-2.03730935e-01 -8.21976010e-01  1.35620001e+03]
 [ 3.37559661e-01  1.16054153e-01  1.35620600e+03]
 [-7.14850596e-01  4.89450719e-01  1.35621198e+03]]
IOCSV___Inner_and_Outer___0
[[-2.92353866e-01  3.94190890e-03 -3.23510395e-04]
 [-5.66806347e-01 -9.71765320e-04 -5.20750889e-04]
 [ 1.99653675e-01 -5.08071870e-03 -8.34048393e-04]
 ...
 [ 2.96659114e-01 -2.28915040e-01  1.37517364e+03]
 [ 3.59506593e-01  1.16355278e-02  1.37517383e+03]
 [ 4.24481704e-01  4.64760421e-01  1.37517399e+03]]
IOCSV___Inner_and_Outer___1
[[ 1.17498993e-01 -5.98907783e-03 -7.12471975e-05]
 [ 6.57936097e-01 -3.81877011e-03 -1.38940243e-04]
 [-6.82667859e-01 -4.92830945e-03 -2.07768847e-04]
 ...
 [ 2.50320606e-01  1.88210789e-01  1.24572414e+03]
 [ 1.27131257e-01 -1.14400826e-01  1.24572984e+03]
 [-5.01751983e-01  8.47155229e-01  1.24573548e+03]]
IOCSV___

test:   0%|          | 0/5 [00:00<?, ?it/s]

ICSV: 0it [00:00, ?it/s]

IBCSV:   0%|          | 0/4 [00:00<?, ?it/s]

[[-1.93415877e-01 -4.31867245e-03 -3.82638441e-06]
 [ 2.83375124e-01 -1.69723335e-03 -1.10891327e-04]
 [-1.48595365e-01  9.17259436e-03 -1.91446873e-04]
 ...
 [ 5.13415550e-01  6.59785700e-02  1.48979837e+03]
 [-1.83477205e+00  1.78255416e-01  1.48979926e+03]
 [-3.89810437e-01  1.38519277e-01  1.48980000e+03]]
IBCSV___Inner_and_Ball___0
[[-5.76469093e-01  1.74026939e-02  1.78756779e-05]
 [-5.05598792e-01  1.72929592e-02  3.98089804e-05]
 [ 1.07667137e+00  1.87926662e-02  5.58445728e-05]
 ...
 [-5.91191827e-01  3.57527676e-02  1.40183002e+03]
 [-8.32717814e-01 -6.67451319e-01  1.40183314e+03]
 [-2.62053928e+00 -3.04686822e-01  1.40183646e+03]]
IBCSV___Inner_and_Ball___1
[[ 4.81101096e-02  8.48370455e-03 -1.19462419e-03]
 [ 1.05476711e+00  8.16669331e-03 -7.49039204e-04]
 [ 1.63533052e+00  1.66711295e-02 -1.05612604e-03]
 ...
 [-6.14199527e-01 -1.18921524e+00  1.31676995e+03]
 [-1.96262882e-01  1.10781772e+00  1.31677119e+03]
 [-1.61352259e+00  6.81711940e-01  1.31677288e+03]]
IBCSV___In

BCSV:   0%|          | 0/8 [00:00<?, ?it/s]

[[-1.31655622e+00 -5.66263770e-01  1.56432739e-03]
 [ 4.35125966e-01 -1.18319203e+00  2.59454745e-03]
 [-1.86441630e-01 -9.77762649e-01  4.26894358e-03]
 ...
 [-7.29164873e-01  1.59883360e-02  1.44359639e+03]
 [ 3.08473880e-01  1.92803758e-02  1.44359773e+03]
 [ 5.37563271e-01  6.47799882e-03  1.44360000e+03]]
BCSV___Ball___0
[[-4.15116469e-01  2.00119402e-02 -1.22647318e-04]
 [ 8.70284857e-01  2.57364316e-02 -2.17426266e-04]
 [-7.25043727e-01  1.23853814e-02 -1.75373202e-04]
 ...
 [-1.30529013e+00 -1.00133121e+00  1.44826572e+03]
 [-3.11057529e-01  1.04831105e+00  1.44826668e+03]
 [-1.47094069e+00 -4.54383188e-01  1.44826773e+03]]
BCSV___Ball___1
[[-5.11298370e+01 -1.91694298e-02  1.48680000e+03]
 [ 2.71409332e+01 -2.45927960e-03  1.48679311e+03]
 [ 5.68805098e+00 -1.59078718e-02  1.48678698e+03]
 ...
 [-4.99935264e-01 -2.24019655e-01  5.81167977e-03]
 [ 1.20570713e+00  7.93586426e-01  5.07070134e-03]
 [ 2.91001683e-01 -1.25702517e+00  2.31389018e-03]]
BCSV___Ball___2
[[ 8.05132951e-0

In [77]:
h5_file=H5_FILE
window_size=128
stride=1
concat=True
datasets = defaultdict(list)
f = h5py.File(h5_file, 'r')
for key in f.keys():
    dataset_name, label, file_idx = key.split('___')
    datasets[dataset_name].append(
        UnwindowedDataset(
            data=f[key],
            dataset_name=dataset_name,
            descriptions=f[key].attrs["descriptions"],
            label=label
        )
    )

if window_size and stride:
    for dataset_name in datasets:
        datasets[dataset_name] = [
            dataset.window(window_size=window_size, stride=stride)
            for dataset in datasets[dataset_name]
        ]

if concat:
    for dataset_name in datasets:
        datasets[dataset_name] = torch.utils.data.ConcatDataset(
            datasets[dataset_name]
        )



<HDF5 dataset "BCSV___Ball___0": shape (222208, 3), type "<f8">
<HDF5 dataset "BCSV___Ball___1": shape (256000, 3), type "<f8">
<HDF5 dataset "BCSV___Ball___2": shape (205824, 3), type "<f8">
<HDF5 dataset "BCSV___Ball___3": shape (256000, 3), type "<f8">
<HDF5 dataset "BCSV___Ball___4": shape (256000, 3), type "<f8">
<HDF5 dataset "BCSV___Ball___5": shape (180736, 3), type "<f8">
<HDF5 dataset "BCSV___Ball___6": shape (256000, 3), type "<f8">
<HDF5 dataset "BCSV___Ball___7": shape (218112, 3), type "<f8">
<HDF5 dataset "IBCSV___Inner_and_Ball___0": shape (256000, 3), type "<f8">
<HDF5 dataset "IBCSV___Inner_and_Ball___1": shape (256000, 3), type "<f8">
<HDF5 dataset "IBCSV___Inner_and_Ball___2": shape (256000, 3), type "<f8">
<HDF5 dataset "IBCSV___Inner_and_Ball___3": shape (256000, 3), type "<f8">
<HDF5 dataset "IOCSV___Inner_and_Outer___0": shape (256000, 3), type "<f8">
<HDF5 dataset "IOCSV___Inner_and_Outer___1": shape (256000, 3), type "<f8">
<HDF5 dataset "IOCSV___Inner_and_Out

In [78]:
print(list(datasets.keys()))

['BCSV', 'IBCSV', 'IOCSV', 'OCSV']


In [79]:
pprint(datasets['BCSV'])

In [85]:
datasets['IBCSV'][0]

Data(data=tensor([[-1.9342e-01, -4.3187e-03, -3.8264e-06],
        [ 2.8338e-01, -1.6972e-03, -1.1089e-04],
        [-1.4860e-01,  9.1726e-03, -1.9145e-04],
        [ 4.5684e-02,  1.4135e-02, -4.4621e-04],
        [ 7.4934e-02, -7.4620e-04, -5.4794e-04],
        [ 3.3499e-01, -3.2924e-05, -5.3409e-04],
        [ 9.8289e-02, -1.3652e-02, -4.6163e-04],
        [-3.5176e-01, -3.6822e-04, -5.8462e-04],
        [-5.8498e-01, -3.2091e-03, -6.2347e-04],
        [ 1.2883e-01,  1.5738e-02, -8.4377e-04],
        [-1.2998e+00, -4.1541e-03, -9.9924e-04],
        [ 9.7666e-01, -2.0447e-03, -1.0283e-03],
        [-1.3347e+00, -2.0462e-02, -8.9044e-04],
        [ 2.0381e-01, -7.3181e-03, -9.5609e-04],
        [ 5.0050e-01, -1.2079e-02, -1.0130e-03],
        [-5.9599e-01,  5.4782e-03, -1.1574e-03],
        [ 6.4868e-01, -1.7460e-03, -1.3743e-03],
        [-4.2621e-01, -8.3057e-03, -1.4342e-03],
        [-9.8998e-01, -1.5865e-02, -1.3641e-03],
        [ 4.6674e-03, -1.7944e-02, -1.3287e-03],
        [ 

In [81]:
pprint(datasets['BCSV'][0].__dict__.keys())

dict_keys(['data', 'descriptions', 'label', 'dataset_name', 'positions'])


In [83]:
pprint(type(datasets['BCSV'][0].data))
pprint(type(datasets['BCSV'][0].descriptions))
pprint(type(datasets['BCSV'][0].label))
pprint(type(datasets['BCSV'][0].dataset_name))

<class 'torch.Tensor'>
<class 'list'>
<class 'str'>
<class 'str'>


In [162]:
from collections import defaultdict
from ftse.data.Dataset import UnwindowedDataset
from tqdm.auto import tqdm
import os
import h5py
import numpy as np
import pandas as pd
import torch

os.environ["HDF5_USE_FILE_LOCKING"] = "FALSE"


ROOT_DIRS = [
    '/data/TimeSeriesResearch/datasets/c3server_labelled_separated/',
    '/data/TimeSeriesResearch/datasets/liu_ice_processed_labelled_separated/',
    '/data/TimeSeriesResearch/datasets/kaggle/processed/processed_datasets_labelled_separated/',
    '/data/TimeSeriesResearch/datasets/Satya/'
]

H5_FILE = '/data/TimeSeriesResearch/datasets/satya_data2.h5'


def create_h5py_dataset_from_root_dirs(root_dirs=ROOT_DIRS, h5_file=H5_FILE):
    with h5py.File(h5_file, "w") as h5f:
        # Iterate over each root directory.
        for root_dir in root_dirs:
            print("root", root_dir)
            # Use the basename of the root directory as a prefix
            root_prefix = os.path.basename(os.path.normpath(root_dir))
            # Iterate over dataset folders in the current root directory.
            for dataset_folder in tqdm(os.listdir(root_dir), desc=f"Datasets in {root_dir}"):
                print("dataset_folder", dataset_folder)
                dataset_path = os.path.join(root_dir, dataset_folder)
                if not os.path.isdir(dataset_path):
                    print("skipping", dataset_path)
                    print("\n"*50)
                    continue  # Skip non-directory items

                # Dictionary to track file indices for each label within this dataset folder.
                label_counts = {}

                # Iterate over each CSV file in the current dataset folder.
                for csv_file in tqdm(os.listdir(dataset_path), desc=dataset_folder, leave=False):
                    # Process only CSV files.
                    if not csv_file.lower().endswith(".csv"):
                        continue

                    # Example filename: "file_5_Normal Operation.csv"
                    # Extract label: take everything after the second underscore and strip ".csv".
                    parts = csv_file.split('_')
                    if len(parts) >= 3:
                        label = '_'.join(parts[2:]).replace('.csv', '')
                    else:
                        label = "Unknown"

                    # Initialize or update the file index counter for this label.
                    if label not in label_counts:
                        label_counts[label] = 0
                    file_idx = label_counts[label]
                    label_counts[label] += 1

                    # Read the CSV file.
                    csv_path = os.path.join(dataset_path, csv_file)
                    df = pd.read_csv(csv_path)
                    # Drop unwanted columns.
                    cols_to_drop = ['Unnamed: 0', 'time_sec', 'Time', 'Label']
                    df = df.drop([col for col in cols_to_drop if col in df.columns], axis=1)
                    # Save the column names as metadata.
                    column_names = df.columns.tolist()
                    data_array = df.to_numpy()

                    # Create a flat key in the format:
                    # "root_prefix___dataset_folder___label___file_idx"
                    key = f"{dataset_folder}___{label}___{file_idx}"
                    dset = h5f.create_dataset(key, data=data_array)
                    dset.attrs["descriptions"] = list(column_names)

    print("Flat HDF5 file created successfully:", h5_file)


def load_h5py_dataset(h5_file=H5_FILE, window_size=None, stride=None, concat=False):
    datasets = defaultdict(list)
    f = h5py.File(h5_file, 'r')
    for key in f.keys():
        dataset_name, label, file_idx = key.split('___')
        datasets[dataset_name].append(
            UnwindowedDataset(
                data=f[key],
                dataset_name=dataset_name,
                descriptions=f[key].attrs["descriptions"],
                label=label
            )
        )

    if window_size and stride:
        for dataset_name in datasets:
            datasets[dataset_name] = [
                dataset.window(window_size=window_size, stride=stride)
                for dataset in datasets[dataset_name]
            ]

    if concat:
        for dataset_name in datasets:
            datasets[dataset_name] = torch.utils.data.ConcatDataset(
                datasets[dataset_name]
            )

    return datasets



In [163]:
create_h5py_dataset_from_root_dirs()

root /data/TimeSeriesResearch/datasets/c3server_labelled_separated/


Datasets in /data/TimeSeriesResearch/datasets/c3server_labelled_separated/:   0%|          | 0/1 [00:00<?, ?it…

dataset_folder c3server


c3server:   0%|          | 0/20 [00:00<?, ?it/s]

root /data/TimeSeriesResearch/datasets/liu_ice_processed_labelled_separated/


Datasets in /data/TimeSeriesResearch/datasets/liu_ice_processed_labelled_separated/:   0%|          | 0/1 [00:…

dataset_folder liu


liu:   0%|          | 0/15 [00:00<?, ?it/s]

root /data/TimeSeriesResearch/datasets/kaggle/processed/processed_datasets_labelled_separated/


Datasets in /data/TimeSeriesResearch/datasets/kaggle/processed/processed_datasets_labelled_separated/:   0%|  …

dataset_folder MetroPT-3 Dataset


MetroPT-3 Dataset:   0%|          | 0/12 [00:00<?, ?it/s]

dataset_folder SKAB - Skoltech Anomaly Benchmark


SKAB - Skoltech Anomaly Benchmark:   0%|          | 0/102 [00:00<?, ?it/s]

dataset_folder Household Electric Power Consumption


Household Electric Power Consumption:   0%|          | 0/1 [00:00<?, ?it/s]

dataset_folder Gas sensor array temperature modulation


Gas sensor array temperature modulation:   0%|          | 0/13 [00:00<?, ?it/s]

dataset_folder Appliances energy prediction Data Set


Appliances energy prediction Data Set:   0%|          | 0/1 [00:00<?, ?it/s]

dataset_folder Machinery Fault Diagnosis


Machinery Fault Diagnosis:   0%|          | 0/1951 [00:00<?, ?it/s]

dataset_folder Predictive Maintenance Of Hydraulics System


Predictive Maintenance Of Hydraulics System:   0%|          | 0/2205 [00:00<?, ?it/s]

dataset_folder Unleashing the Power of Wearables


Unleashing the Power of Wearables:   0%|          | 0/6971 [00:00<?, ?it/s]

root /data/TimeSeriesResearch/datasets/Satya/


Datasets in /data/TimeSeriesResearch/datasets/Satya/:   0%|          | 0/19 [00:00<?, ?it/s]

dataset_folder Accelerometer


Accelerometer:   0%|          | 0/18 [00:00<?, ?it/s]

dataset_folder BCSV


BCSV:   0%|          | 0/8 [00:00<?, ?it/s]

dataset_folder Wyoming


Wyoming:   0%|          | 0/16 [00:00<?, ?it/s]

dataset_folder Maryland


Maryland:   0%|          | 0/21 [00:00<?, ?it/s]

dataset_folder California


California:   0%|          | 0/111 [00:00<?, ?it/s]

dataset_folder Delaware


Delaware:   0%|          | 0/6 [00:00<?, ?it/s]

dataset_folder Airquality_pattern


Airquality_pattern:   0%|          | 0/3 [00:00<?, ?it/s]

dataset_folder HAR


HAR:   0%|          | 0/4 [00:00<?, ?it/s]

dataset_folder Florida


Florida:   0%|          | 0/54 [00:00<?, ?it/s]

dataset_folder Texas


Texas:   0%|          | 0/6 [00:00<?, ?it/s]

dataset_folder Michigan


Michigan:   0%|          | 0/10 [00:00<?, ?it/s]

dataset_folder OCSV


OCSV:   0%|          | 0/9 [00:00<?, ?it/s]

dataset_folder turbofan


turbofan:   0%|          | 0/5 [00:00<?, ?it/s]

dataset_folder NewYork


NewYork:   0%|          | 0/6 [00:00<?, ?it/s]

dataset_folder IOCSV


IOCSV:   0%|          | 0/5 [00:00<?, ?it/s]

dataset_folder Illinois


Illinois:   0%|          | 0/9 [00:00<?, ?it/s]

dataset_folder Gyrometer


Gyrometer:   0%|          | 0/18 [00:00<?, ?it/s]

dataset_folder IBCSV


IBCSV:   0%|          | 0/4 [00:00<?, ?it/s]

dataset_folder sleepedf


sleepedf:   0%|          | 0/28 [00:00<?, ?it/s]

Flat HDF5 file created successfully: /data/TimeSeriesResearch/datasets/satya_data2.h5


In [164]:
h5_ds = load_h5py_dataset(window_size=128, stride=1, concat=True)

In [165]:
print(h5_ds.keys())

dict_keys(['Accelerometer', 'Airquality_pattern', 'Appliances energy prediction Data Set', 'BCSV', 'California', 'Delaware', 'Florida', 'Gas sensor array temperature modulation', 'Gyrometer', 'HAR', 'Household Electric Power Consumption', 'IBCSV', 'IOCSV', 'Illinois', 'Machinery Fault Diagnosis', 'Maryland', 'MetroPT-3 Dataset', 'Michigan', 'NewYork', 'OCSV', 'Predictive Maintenance Of Hydraulics System', 'SKAB - Skoltech Anomaly Benchmark', 'Texas', 'Unleashing the Power of Wearables', 'Wyoming', 'c3server', 'liu', 'sleepedf', 'turbofan'])


In [170]:
h5_ds["HAR"][200]

Data(data=tensor([[-1.7312e-03,  5.4721e-03,  4.4153e-03],
        [ 3.9997e-04,  1.4475e-04, -7.7101e-03],
        [-5.9090e-02,  2.3032e-01,  1.8095e-02],
        [ 9.0877e-03, -4.4330e-02, -3.6740e-02],
        [ 6.5123e-03, -4.6307e-03,  1.2650e-02],
        [ 2.8620e-04,  6.4749e-03,  4.2130e-03],
        [ 2.6204e-03,  3.0584e-03, -1.7183e-03],
        [-2.7738e-04,  1.5401e-04, -2.0406e-03],
        [ 2.0981e-03,  2.6142e-03,  7.6258e-03],
        [-4.8276e-04,  1.8593e-03, -4.9718e-03],
        [ 8.2107e-04,  7.0453e-05,  2.4144e-04],
        [-2.6471e-03,  4.1843e-03,  1.6769e-03],
        [-3.5108e-03, -4.1480e-03, -2.2711e-03],
        [ 4.5778e-04,  1.2255e-02, -5.3278e-02],
        [ 2.8814e-02, -1.1116e-02,  9.3829e-03],
        [ 5.2609e-03, -2.8241e-03, -5.0431e-04],
        [-1.7224e-03,  3.0544e-03,  7.5523e-04],
        [ 6.4456e-03,  3.3897e-03, -5.5996e-03],
        [-2.8074e-03,  3.5505e-04, -1.2833e-03],
        [-3.7072e-03, -1.3995e-03,  1.5702e-03],
        [ 

In [4]:
import pandas as pd
import mne

In [156]:
raw = mne.io.read_raw_edf("test/sleepedf/SC4101E0-PSG.edf", preload=True)
print(raw.ch_names)

Extracting EDF parameters from /workspace/research/ftse/ftse/notebooks/test/sleepedf/SC4101E0-PSG.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 8159999  =      0.000 ... 81599.990 secs...


/tmp/ipykernel_704971/3814463732.py:1: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf("test/sleepedf/SC4101E0-PSG.edf", preload=True)
/tmp/ipykernel_704971/3814463732.py:1: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf("test/sleepedf/SC4101E0-PSG.edf", preload=True)
/tmp/ipykernel_704971/3814463732.py:1: RuntimeWarning: Highpass cutoff frequency 16.0 is greater than lowpass cutoff frequency 0.7, setting values to 0 and Nyquist.
  raw = mne.io.read_raw_edf("test/sleepedf/SC4101E0-PSG.edf", preload=True)


['EEG Fpz-Cz', 'EEG Pz-Oz', 'EOG horizontal', 'Resp oro-nasal', 'EMG submental', 'Temp rectal', 'Event marker']


In [157]:
data, times = raw.get_data(return_times=True)
df = pd.DataFrame(data.T, columns=raw.ch_names)
df["timestamp"] = times

In [158]:
df.head()

EEG Fpz-Cz  EEG Pz-Oz  EOG horizontal  Resp oro-nasal  EMG submental  \
0 -2.893773e-07   0.000006       -0.000064      800.000000       0.000004   
1  1.510867e-06   0.000008       -0.000056      804.667024       0.000004   
2 -2.184371e-06   0.000008       -0.000074      809.223229       0.000004   
3 -9.987790e-08   0.000008       -0.000062      813.667591       0.000004   
4 -1.994872e-06   0.000010       -0.000053      817.999151       0.000004   

   Temp rectal  Event marker  timestamp  
0    36.899636   1001.000000       0.00  
1    36.899330   1000.994589       0.01  
2    36.899020   1000.988551       0.02  
3    36.898708   1000.981640       0.03  
4    36.898394   1000.973607       0.04

In [159]:
columns_mapping={
    'EEG Fpz-Cz' : 'EEG channel 1 (frontal to central)',
    'EEG Pz-Oz' : 'EEG channel 2 (parietal to occipital)',
    'EOG horizontal' : 'Electrooculogram (eye movements)',
    'EMG submental' : 'Electromyogram (muscle activity)'
}
df.drop(columns=["Event marker", "timestamp"], inplace=True)
df.rename(columns = columns_mapping, inplace=True)
df.reset_index(drop=True, inplace=True)

In [160]:
df.to_csv("sleepedf/file_14_Healthy.csv")

In [10]:
import os
import shutil
from tqdm import tqdm

OLD_ROOT = "/data/TimeSeriesResearch/datasets/Satya"
NEW_ROOT = "/data/TimeSeriesResearch/datasets/Satya_New"

def restructure_dataset(old_root=OLD_ROOT, new_root=NEW_ROOT):
    os.makedirs(new_root, exist_ok=True)

    # Iterate over each folder in the old root directory
    for folder in tqdm(os.listdir(old_root), desc="Processing Folders"):
        folder_path = os.path.join(old_root, folder)
        
        # Skip non-directory entries
        if not os.path.isdir(folder_path):
            continue

        # Iterate over each file in the folder
        for file_name in os.listdir(folder_path):
            # Process only CSV files
            if not file_name.lower().endswith(".csv"):
                continue
            
            # Extract label and index from the file name
            parts = file_name.split('_')
            if len(parts) >= 3:
                label = '_'.join(parts[2:]).replace('.csv', '')
                index = parts[1]
            else:
                label = "Unknown"
                index = parts[1] if len(parts) > 1 else "0"

            # Create the destination folder structure
            label_folder = os.path.join(new_root, folder, label)
            os.makedirs(label_folder, exist_ok=True)

            # Construct destination filename as "file_{index}.csv"
            new_file_name = f"file_{index}.csv"
            src_path = os.path.join(folder_path, file_name)
            dst_path = os.path.join(label_folder, new_file_name)

            # Move the file to the new location
            try:
                shutil.copy(src_path, dst_path)
                print(f"Moved: {src_path} -> {dst_path}")
            except Exception as e:
                print(f"Error moving {src_path} to {dst_path}: {e}")

    print("Restructuring complete.")

restructure_dataset()


Processing Folders:   6%|█████████████▋                                                                                                                                                                                                                           | 1/17 [00:00<00:02,  5.52it/s]

Moved: /data/TimeSeriesResearch/datasets/Satya/Accelerometer/file_7_FloorMove.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Accelerometer/FloorMove/file_7.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Accelerometer/file_0_BuildingElevatorMove.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Accelerometer/BuildingElevatorMove/file_0.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Accelerometer/file_5_FloorMove.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Accelerometer/FloorMove/file_5.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Accelerometer/file_0_OutdoorMove.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Accelerometer/OutdoorMove/file_0.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Accelerometer/file_2_FloorMove.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Accelerometer/FloorMove/file_2.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Accelerometer/file_0_EscalatorMove.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Accelerometer/Escalat

Processing Folders:  12%|███████████████████████████▍                                                                                                                                                                                                             | 2/17 [00:00<00:05,  2.66it/s]

Moved: /data/TimeSeriesResearch/datasets/Satya/BCSV/file_2_Ball.csv -> /data/TimeSeriesResearch/datasets/Satya_New/BCSV/Ball/file_2.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/BCSV/file_4_Ball.csv -> /data/TimeSeriesResearch/datasets/Satya_New/BCSV/Ball/file_4.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/BCSV/file_7_Ball.csv -> /data/TimeSeriesResearch/datasets/Satya_New/BCSV/Ball/file_7.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/BCSV/file_0_Ball.csv -> /data/TimeSeriesResearch/datasets/Satya_New/BCSV/Ball/file_0.csv


Processing Folders:  18%|█████████████████████████████████████████                                                                                                                                                                                                | 3/17 [00:00<00:03,  3.79it/s]

Moved: /data/TimeSeriesResearch/datasets/Satya/Wyoming/file_5_SO2.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Wyoming/SO2/file_5.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Wyoming/file_6_SO2.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Wyoming/SO2/file_6.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Wyoming/file_8_SO2.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Wyoming/SO2/file_8.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Wyoming/file_12_SO2.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Wyoming/SO2/file_12.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Wyoming/file_1_SO2.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Wyoming/SO2/file_1.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Wyoming/file_10_SO2.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Wyoming/SO2/file_10.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Wyoming/file_13_SO2.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Wyoming/SO2/file_13.csv
Moved: /data/T

Processing Folders:  24%|██████████████████████████████████████████████████████▊                                                                                                                                                                                  | 4/17 [00:00<00:02,  4.43it/s]

Moved: /data/TimeSeriesResearch/datasets/Satya/Maryland/file_19_Ozone.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Maryland/Ozone/file_19.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Maryland/file_18_Ozone.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Maryland/Ozone/file_18.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Maryland/file_16_Ozone.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Maryland/Ozone/file_16.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Maryland/file_11_Ozone.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Maryland/Ozone/file_11.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Maryland/file_1_Ozone.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Maryland/Ozone/file_1.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Maryland/file_7_Ozone.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Maryland/Ozone/file_7.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Maryland/file_6_Ozone.csv -> /data/TimeSeriesResearch/datasets/Satya_

Processing Folders:  29%|████████████████████████████████████████████████████████████████████▌                                                                                                                                                                    | 5/17 [00:01<00:05,  2.12it/s]

Moved: /data/TimeSeriesResearch/datasets/Satya/California/file_22_CO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/California/CO/file_22.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/California/file_109_CO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/California/CO/file_109.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/California/file_16_CO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/California/CO/file_16.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/California/file_42_CO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/California/CO/file_42.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/California/file_19_CO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/California/CO/file_19.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/California/file_98_CO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/California/CO/file_98.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/California/file_78_CO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Ca

Processing Folders:  47%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                           | 8/17 [00:02<00:02,  3.34it/s]

Moved: /data/TimeSeriesResearch/datasets/Satya/Florida/file_10_PM25.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Florida/PM25/file_10.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Florida/file_16_PM25.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Florida/PM25/file_16.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Florida/file_47_PM25.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Florida/PM25/file_47.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Florida/file_44_PM25.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Florida/PM25/file_44.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Florida/file_38_PM25.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Florida/PM25/file_38.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Florida/file_18_PM25.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Florida/PM25/file_18.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Florida/file_13_PM25.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Florida/PM25/file

Processing Folders:  59%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                               | 10/17 [00:02<00:01,  4.63it/s]

Moved: /data/TimeSeriesResearch/datasets/Satya/Michigan/file_1_CO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Michigan/CO/file_1.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Michigan/file_5_CO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Michigan/CO/file_5.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Michigan/file_4_CO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Michigan/CO/file_4.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Michigan/file_7_CO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Michigan/CO/file_7.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Michigan/file_8_CO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Michigan/CO/file_8.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Michigan/file_6_CO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Michigan/CO/file_6.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Michigan/file_2_CO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Michigan/CO/file_2.csv
Moved: /data/TimeSer

Processing Folders:  65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                  | 11/17 [00:03<00:01,  3.47it/s]

Moved: /data/TimeSeriesResearch/datasets/Satya/OCSV/file_5_Outer_and_Ball.csv -> /data/TimeSeriesResearch/datasets/Satya_New/OCSV/Outer_and_Ball/file_5.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/OCSV/file_1_Outer_and_Ball.csv -> /data/TimeSeriesResearch/datasets/Satya_New/OCSV/Outer_and_Ball/file_1.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/OCSV/file_3_Outer_and_Ball.csv -> /data/TimeSeriesResearch/datasets/Satya_New/OCSV/Outer_and_Ball/file_3.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/turbofan/file_0_Unknown.csv -> /data/TimeSeriesResearch/datasets/Satya_New/turbofan/Unknown/file_0.csv


Processing Folders:  71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                    | 12/17 [00:03<00:01,  3.84it/s]

Moved: /data/TimeSeriesResearch/datasets/Satya/turbofan/file_1_Unknown.csv -> /data/TimeSeriesResearch/datasets/Satya_New/turbofan/Unknown/file_1.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/turbofan/file_2_Unknown.csv -> /data/TimeSeriesResearch/datasets/Satya_New/turbofan/Unknown/file_2.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/turbofan/file_3_Unknown.csv -> /data/TimeSeriesResearch/datasets/Satya_New/turbofan/Unknown/file_3.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/NewYork/file_4_PM1.csv -> /data/TimeSeriesResearch/datasets/Satya_New/NewYork/PM1/file_4.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/NewYork/file_0_PM1.csv -> /data/TimeSeriesResearch/datasets/Satya_New/NewYork/PM1/file_0.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/NewYork/file_2_PM1.csv -> /data/TimeSeriesResearch/datasets/Satya_New/NewYork/PM1/file_2.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/NewYork/file_3_PM1.csv -> /data/TimeSeriesResearch/datasets/Satya_New/NewYork/PM1/f

Processing Folders:  82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                         | 14/17 [00:03<00:00,  4.40it/s]

Moved: /data/TimeSeriesResearch/datasets/Satya/IOCSV/file_1_Inner_and_Outer.csv -> /data/TimeSeriesResearch/datasets/Satya_New/IOCSV/Inner_and_Outer/file_1.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Illinois/file_7_NO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Illinois/NO/file_7.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Illinois/file_4_NO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Illinois/NO/file_4.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Illinois/file_1_NO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Illinois/NO/file_1.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Illinois/file_5_NO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Illinois/NO/file_5.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Illinois/file_6_NO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Illinois/NO/file_6.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Illinois/file_2_NO.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Illinois/NO/file_2.csv


Processing Folders:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎             | 16/17 [00:03<00:00,  5.08it/s]

Moved: /data/TimeSeriesResearch/datasets/Satya/Gyrometer/file_0_BuildingStairMove.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Gyrometer/BuildingStairMove/file_0.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Gyrometer/file_1_BuildingElevatorMove.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Gyrometer/BuildingElevatorMove/file_1.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Gyrometer/file_1_OutdoorMove.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Gyrometer/OutdoorMove/file_1.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Gyrometer/file_0_FloorMove.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Gyrometer/FloorMove/file_0.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Gyrometer/file_3_FloorMove.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Gyrometer/FloorMove/file_3.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/Gyrometer/file_1_FloorMove.csv -> /data/TimeSeriesResearch/datasets/Satya_New/Gyrometer/FloorMove/file_1.csv
Moved: /data/TimeSerie

Processing Folders: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:04<00:00,  4.04it/s]

Moved: /data/TimeSeriesResearch/datasets/Satya/IBCSV/file_1_Inner_and_Ball.csv -> /data/TimeSeriesResearch/datasets/Satya_New/IBCSV/Inner_and_Ball/file_1.csv
Moved: /data/TimeSeriesResearch/datasets/Satya/IBCSV/file_2_Inner_and_Ball.csv -> /data/TimeSeriesResearch/datasets/Satya_New/IBCSV/Inner_and_Ball/file_2.csv
Restructuring complete.


In [4]:
import h5py
import os
import pandas as pd
from tqdm import tqdm

H5_FILE = '/data/TimeSeriesResearch/datasets/satya_data1.h5'
OUTPUT_DIR = '/data/TimeSeriesResearch/datasets/Satya_Restored/'

def restore_csv_with_labels(h5_file, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    
    with h5py.File(h5_file, "r") as h5f:
        # Iterate over each dataset key in the HDF5 file
        for key in tqdm(h5f.keys(), desc="Restoring datasets"):
            # Extract metadata and data
            dset = h5f[key]
            data_array = dset[()]
            column_names = dset.attrs.get("descriptions", [])
            
            # Split the key to reconstruct the original folder structure and filename
            dataset_folder, label, file_idx = key.split('___')
            
            # Construct the output folder path
            folder_path = os.path.join(output_dir, dataset_folder)
            os.makedirs(folder_path, exist_ok=True)
            
            # Filename construction with label
            csv_filename = f"file_{file_idx}_{label}.csv"
            csv_path = os.path.join(folder_path, csv_filename)
            
            # Convert the data array to a DataFrame
            df = pd.DataFrame(data_array, columns=column_names)
            
            # Save the DataFrame to a CSV file
            df.to_csv(csv_path, index=False)
    
    print(f"Data restored with labels to {output_dir}")

# Run the restoration process
restore_csv_with_labels(H5_FILE, OUTPUT_DIR)


Restoring datasets:   2%|████▉                                                                                                                                                                                                                             | 254/11587 [01:46<1:19:02,  2.39it/s]


KeyboardInterrupt: 

In [5]:
import h5py
import os
import pandas as pd
from tqdm import tqdm

H5_FILE = '/data/TimeSeriesResearch/datasets/satya_data1.h5'
OUTPUT_DIR = '/data/TimeSeriesResearch/datasets/Satya_Restored/'

# Specify the folders to be restored
FOLDERS_TO_RESTORE = [
    "Accelerometer", "Airquality_pattern", "BCSV", "California", "Delaware", 
    "Florida", "Gyrometer", "HAR", "IBCSV", "IOCSV", "Illinois", "Maryland", 
    "Michigan", "NewYork", "OCSV", "Texas", "Wyoming", "sleepedf", "turbofan"
]

def restore_selected_folders(h5_file, output_dir, folders_to_restore):
    os.makedirs(output_dir, exist_ok=True)
    
    with h5py.File(h5_file, "r") as h5f:
        # Iterate over each dataset key in the HDF5 file
        for key in tqdm(h5f.keys(), desc="Restoring datasets"):
            # Extract metadata and data
            dset = h5f[key]
            data_array = dset[()]
            column_names = dset.attrs.get("descriptions", [])
            
            # Split the key to reconstruct the original folder structure and filename
            dataset_folder, label, file_idx = key.split('___')
            
            # Only proceed if the folder is in the specified list
            if dataset_folder not in folders_to_restore:
                continue
            
            # Construct the output folder path
            folder_path = os.path.join(output_dir, dataset_folder)
            os.makedirs(folder_path, exist_ok=True)
            
            # Filename construction with label
            csv_filename = f"file_{file_idx}_{label}.csv"
            csv_path = os.path.join(folder_path, csv_filename)
            
            # Convert the data array to a DataFrame
            df = pd.DataFrame(data_array, columns=column_names)
            
            # Save the DataFrame to a CSV file
            df.to_csv(csv_path, index=False)
    
    print(f"Selected folders restored with labels to {output_dir}")

# Run the selective restoration process
restore_selected_folders(H5_FILE, OUTPUT_DIR, FOLDERS_TO_RESTORE)


Restoring datasets: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11587/11587 [02:47<00:00, 69.17it/s]

Selected folders restored with labels to /data/TimeSeriesResearch/datasets/Satya_Restored/


In [17]:
import pandas as pd
df=pd.read_csv("/data/TimeSeriesResearch/datasets/Satya_New/turbofan/Unknown/file_1.csv")

In [18]:
df.head()

op_setting_1  op_setting_2  op_setting_3  (Fan inlet temperature) (◦R)  \
0       -0.0007       -0.0004         100.0                        518.67   
1        0.0019       -0.0003         100.0                        518.67   
2       -0.0043        0.0003         100.0                        518.67   
3        0.0007        0.0000         100.0                        518.67   
4       -0.0019       -0.0002         100.0                        518.67   

   (LPC outlet temperature) (◦R)  (HPC outlet temperature) (◦R)  \
0                         641.82                        1589.70   
1                         642.15                        1591.82   
2                         642.35                        1587.99   
3                         642.35                        1582.79   
4                         642.37                        1582.85   

   (LPT outlet temperature) (◦R)  (Fan inlet Pressure) (psia)  \
0                        1400.60                        14.62   
1                        1403.14                        14.62   
2                        1404.20                        14.62   
3                        1401.87                        14.62   
4                        1406.22                        14.62   

   (bypass-duct pressure) (psia)  (HPC outlet pressure) (psia)  ...  \
0                          21.61                        554.36  ...   
1                          21.61                        553.75  ...   
2                          21.61                        554.26  ...   
3                          21.61                        554.45  ...   
4                          21.61                        554.00  ...   

   (Ratio of fuel flow to Ps30) (pps/psia)  (Corrected fan speed) (rpm)  \
0                                   521.66                      2388.02   
1                                   522.28                      2388.07   
2                                   522.42                      2388.03   
3                                   522.86                      2388.08   
4                                   522.19                      2388.04   

   (Corrected core speed) (rpm)  (Bypass Ratio)   (Burner fuel-air ratio)  \
0                       8138.62           8.4195                     0.03   
1                       8131.49           8.4318                     0.03   
2                       8133.23           8.4178                     0.03   
3                       8133.83           8.3682                     0.03   
4                       8133.80           8.4294                     0.03   

   (Bleed Enthalpy)  (Required fan speed)  (Required fan conversion speed)  \
0             392.0                2388.0                            100.0   
1             392.0                2388.0                            100.0   
2             390.0                2388.0                            100.0   
3             392.0                2388.0                            100.0   
4             393.0                2388.0                            100.0   

   (High-pressure turbines Cool air flow)  \
0                                   39.06   
1                                   39.00   
2                                   38.95   
3                                   38.88   
4                                   38.90   

   (Low-pressure turbines Cool air flow)  
0                                23.4190  
1                                23.4236  
2                                23.3442  
3                                23.3739  
4                                23.4044  

[5 rows x 24 columns]

In [20]:
root_dirs = ['/data/TimeSeriesResearch/datasets/Satya_New']
for root_dir in root_dirs:
    root_prefix = os.path.basename(os.path.normpath(root_dir))
    print(root_prefix)

    for dataset_folder in tqdm(os.listdir(root_dir), desc=f"Processing {root_dir}"):
        dataset_path = os.path.join(root_dir, dataset_folder)
        if not os.path.isdir(dataset_path):
            continue

        for csv_file in os.listdir(dataset_path):
            if not csv_file.lower().endswith(".csv"):
                print(csv_file)

Satya_New


Processing /data/TimeSeriesResearch/datasets/Satya_New: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 886.93it/s]

BuildingStairMove
OutdoorMove
EscalatorMove
BuildingElevatorMove
FloorMove
IndoorMove
Ball
SO2
Ozone
CO
SO2
Unknown
PM25
Pb
CO
Outer_and_Ball
Unknown
PM1
Inner_and_Outer
NO
BuildingStairMove
OutdoorMove
EscalatorMove
BuildingElevatorMove
FloorMove
IndoorMove
Inner_and_Ball


In [21]:
import os
import h5py
import pandas as pd
from tqdm import tqdm

ROOT_DIRS = [
    '/data/TimeSeriesResearch/datasets/Satya_New'
]

H5_FILE = '/data/TimeSeriesResearch/datasets/satya_new_data1.h5'

def create_h5py_dataset_from_root_dirs_v2(root_dirs=ROOT_DIRS, h5_file=H5_FILE):
    with h5py.File(h5_file, "w") as h5f:
        for root_dir in root_dirs:
            root_prefix = os.path.basename(os.path.normpath(root_dir))

            for folder in tqdm(os.listdir(root_dir), desc=f"Processing {root_dir}"):
                folder_path = os.path.join(root_dir, folder)
                if not os.path.isdir(folder_path):
                    continue
                #For labels
                for subfolder in os.listdir(folder_path):
                    subfolder_path = os.path.join(folder_path, subfolder)
                    if not os.path.isdir(subfolder_path):
                        continue

                    for csv_file in os.listdir(subfolder_path):
                        if not csv_file.lower().endswith(".csv"):
                            continue

                        try:
                            group_path = f"{root_prefix}/{folder}/{subfolder}"
                            group = h5f.require_group(group_path)

                            csv_path = os.path.join(subfolder_path, csv_file)
                            df = pd.read_csv(csv_path)

                            drop_columns = ['Unnamed: 0', 'time_sec', 'Time', 'Label']
                            df = df.drop(columns=[col for col in drop_columns if col in df.columns], errors='ignore')

                            column_names = df.columns.tolist()
                            data_array = df.to_numpy()
                            dataset_name = f"file_{len(group)}"
                            dset = group.create_dataset(dataset_name, data=data_array)
                            dset.attrs["descriptions"] = list(column_names)

                            print(f"Created dataset at: {group_path}/{dataset_name}")

                        except Exception as e:
                            print(f"Error processing {csv_path}: {e}")
                            continue

create_h5py_dataset_from_root_dirs_v2()


Processing /data/TimeSeriesResearch/datasets/Satya_New:   0%|                                                                                                                                                                                                             | 0/17 [00:00<?, ?it/s]

Created dataset at: Satya_New/Accelerometer/BuildingStairMove/file_0
Created dataset at: Satya_New/Accelerometer/BuildingStairMove/file_1
Created dataset at: Satya_New/Accelerometer/OutdoorMove/file_0
Created dataset at: Satya_New/Accelerometer/OutdoorMove/file_1
Created dataset at: Satya_New/Accelerometer/EscalatorMove/file_0
Created dataset at: Satya_New/Accelerometer/EscalatorMove/file_1
Created dataset at: Satya_New/Accelerometer/BuildingElevatorMove/file_0
Created dataset at: Satya_New/Accelerometer/BuildingElevatorMove/file_1
Created dataset at: Satya_New/Accelerometer/FloorMove/file_0
Created dataset at: Satya_New/Accelerometer/FloorMove/file_1
Created dataset at: Satya_New/Accelerometer/FloorMove/file_2
Created dataset at: Satya_New/Accelerometer/FloorMove/file_3
Created dataset at: Satya_New/Accelerometer/FloorMove/file_4
Created dataset at: Satya_New/Accelerometer/FloorMove/file_5
Created dataset at: Satya_New/Accelerometer/FloorMove/file_6
Created dataset at: Satya_New/Accel

Processing /data/TimeSeriesResearch/datasets/Satya_New:  12%|███████████████████████▏                                                                                                                                                                             | 2/17 [00:01<00:09,  1.54it/s]

Created dataset at: Satya_New/BCSV/Ball/file_6
Created dataset at: Satya_New/BCSV/Ball/file_7
Created dataset at: Satya_New/Wyoming/SO2/file_0
Created dataset at: Satya_New/Wyoming/SO2/file_1
Created dataset at: Satya_New/Wyoming/SO2/file_2
Created dataset at: Satya_New/Wyoming/SO2/file_3
Created dataset at: Satya_New/Wyoming/SO2/file_4
Created dataset at: Satya_New/Wyoming/SO2/file_5
Created dataset at: Satya_New/Wyoming/SO2/file_6
Created dataset at: Satya_New/Wyoming/SO2/file_7
Created dataset at: Satya_New/Wyoming/SO2/file_8
Created dataset at: Satya_New/Wyoming/SO2/file_9
Created dataset at: Satya_New/Wyoming/SO2/file_10
Created dataset at: Satya_New/Wyoming/SO2/file_11
Created dataset at: Satya_New/Wyoming/SO2/file_12
Created dataset at: Satya_New/Wyoming/SO2/file_13
Created dataset at: Satya_New/Wyoming/SO2/file_14
Created dataset at: Satya_New/Maryland/Ozone/file_0
Created dataset at: Satya_New/Maryland/Ozone/file_1
Created dataset at: Satya_New/Maryland/Ozone/file_2
Created da

Processing /data/TimeSeriesResearch/datasets/Satya_New:  29%|█████████████████████████████████████████████████████████▉                                                                                                                                           | 5/17 [00:01<00:03,  3.47it/s]

Created dataset at: Satya_New/California/CO/file_65
Created dataset at: Satya_New/California/CO/file_66
Created dataset at: Satya_New/California/CO/file_67
Created dataset at: Satya_New/California/CO/file_68
Created dataset at: Satya_New/California/CO/file_69
Created dataset at: Satya_New/California/CO/file_70
Created dataset at: Satya_New/California/CO/file_71
Created dataset at: Satya_New/California/CO/file_72
Created dataset at: Satya_New/California/CO/file_73
Created dataset at: Satya_New/California/CO/file_74
Created dataset at: Satya_New/California/CO/file_75
Created dataset at: Satya_New/California/CO/file_76
Created dataset at: Satya_New/California/CO/file_77
Created dataset at: Satya_New/California/CO/file_78
Created dataset at: Satya_New/California/CO/file_79
Created dataset at: Satya_New/California/CO/file_80
Created dataset at: Satya_New/California/CO/file_81
Created dataset at: Satya_New/California/CO/file_82
Created dataset at: Satya_New/California/CO/file_83
Created data

Processing /data/TimeSeriesResearch/datasets/Satya_New:  47%|████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                        | 8/17 [00:01<00:01,  5.80it/s]

Created dataset at: Satya_New/Florida/PM25/file_27
Created dataset at: Satya_New/Florida/PM25/file_28
Created dataset at: Satya_New/Florida/PM25/file_29
Created dataset at: Satya_New/Florida/PM25/file_30
Created dataset at: Satya_New/Florida/PM25/file_31
Created dataset at: Satya_New/Florida/PM25/file_32
Created dataset at: Satya_New/Florida/PM25/file_33
Created dataset at: Satya_New/Florida/PM25/file_34
Created dataset at: Satya_New/Florida/PM25/file_35
Created dataset at: Satya_New/Florida/PM25/file_36
Created dataset at: Satya_New/Florida/PM25/file_37
Created dataset at: Satya_New/Florida/PM25/file_38
Created dataset at: Satya_New/Florida/PM25/file_39
Created dataset at: Satya_New/Florida/PM25/file_40
Created dataset at: Satya_New/Florida/PM25/file_41
Created dataset at: Satya_New/Florida/PM25/file_42
Created dataset at: Satya_New/Florida/PM25/file_43
Created dataset at: Satya_New/Florida/PM25/file_44
Created dataset at: Satya_New/Florida/PM25/file_45
Created dataset at: Satya_New/F

Processing /data/TimeSeriesResearch/datasets/Satya_New:  65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                     | 11/17 [00:03<00:01,  3.52it/s]

Created dataset at: Satya_New/OCSV/Outer_and_Ball/file_7
Created dataset at: Satya_New/OCSV/Outer_and_Ball/file_8
Created dataset at: Satya_New/turbofan/Unknown/file_0
Created dataset at: Satya_New/turbofan/Unknown/file_1
Created dataset at: Satya_New/turbofan/Unknown/file_2


Processing /data/TimeSeriesResearch/datasets/Satya_New:  71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                         | 12/17 [00:03<00:01,  3.29it/s]

Created dataset at: Satya_New/turbofan/Unknown/file_3
Created dataset at: Satya_New/NewYork/PM1/file_0
Created dataset at: Satya_New/NewYork/PM1/file_1
Created dataset at: Satya_New/NewYork/PM1/file_2
Created dataset at: Satya_New/NewYork/PM1/file_3
Created dataset at: Satya_New/NewYork/PM1/file_4
Created dataset at: Satya_New/IOCSV/Inner_and_Outer/file_0
Created dataset at: Satya_New/IOCSV/Inner_and_Outer/file_1
Created dataset at: Satya_New/IOCSV/Inner_and_Outer/file_2


Processing /data/TimeSeriesResearch/datasets/Satya_New:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 14/17 [00:04<00:00,  3.03it/s]

Created dataset at: Satya_New/IOCSV/Inner_and_Outer/file_3
Created dataset at: Satya_New/IOCSV/Inner_and_Outer/file_4
Created dataset at: Satya_New/Illinois/NO/file_0
Created dataset at: Satya_New/Illinois/NO/file_1
Created dataset at: Satya_New/Illinois/NO/file_2
Created dataset at: Satya_New/Illinois/NO/file_3
Created dataset at: Satya_New/Illinois/NO/file_4
Created dataset at: Satya_New/Illinois/NO/file_5
Created dataset at: Satya_New/Illinois/NO/file_6
Created dataset at: Satya_New/Illinois/NO/file_7
Created dataset at: Satya_New/Gyrometer/BuildingStairMove/file_0
Created dataset at: Satya_New/Gyrometer/BuildingStairMove/file_1
Created dataset at: Satya_New/Gyrometer/OutdoorMove/file_0
Created dataset at: Satya_New/Gyrometer/OutdoorMove/file_1
Created dataset at: Satya_New/Gyrometer/EscalatorMove/file_0
Created dataset at: Satya_New/Gyrometer/EscalatorMove/file_1
Created dataset at: Satya_New/Gyrometer/BuildingElevatorMove/file_0
Created dataset at: Satya_New/Gyrometer/BuildingElev

Processing /data/TimeSeriesResearch/datasets/Satya_New: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:05<00:00,  3.38it/s]

Created dataset at: Satya_New/IBCSV/Inner_and_Ball/file_2
Created dataset at: Satya_New/IBCSV/Inner_and_Ball/file_3


In [44]:
from collections import defaultdict
from ftse.data.Dataset import UnwindowedDataset
from tqdm.auto import tqdm
import os
import h5py
import numpy as np
import pandas as pd
import torch

def load_h5py_dataset(h5_file=H5_FILE, window_size=None, stride=None, concat=False):
    datasets = defaultdict(list)
    def recursive_group_traversal(group, path=""):
        for key in group.keys():
            item = group[key]

            if isinstance(item, h5py.Group):
                print("item: ", item)
                recursive_group_traversal(item, path + "/" + key)
            elif isinstance(item, h5py.Dataset):
                label = path.split("/")[-1]
                dataset_name = "/".join(path.split("/")[1:-1])

                datasets[dataset_name].append(
                    UnwindowedDataset(
                        data=item,
                        dataset_name=dataset_name,
                        descriptions=item.attrs.get("descriptions", []),
                        label=label
                    )
                )

    f = h5py.File(h5_file, 'r')
    recursive_group_traversal(f)

    if window_size and stride:
        for dataset_name in datasets:
            datasets[dataset_name] = [
                dataset.window(window_size=window_size, stride=stride)
                for dataset in datasets[dataset_name]
            ]

    if concat:
        for dataset_name in datasets:
            datasets[dataset_name] = torch.utils.data.ConcatDataset(
                datasets[dataset_name]
            )

    return datasets

In [45]:
datasets = load_h5py_dataset(H5_FILE, window_size=128, stride=1, concat=True)

item:  <HDF5 group "/Satya_New" (17 members)>
item:  <HDF5 group "/Satya_New/Accelerometer" (6 members)>
item:  <HDF5 group "/Satya_New/Accelerometer/BuildingElevatorMove" (2 members)>
item:  <HDF5 group "/Satya_New/Accelerometer/BuildingStairMove" (2 members)>
item:  <HDF5 group "/Satya_New/Accelerometer/EscalatorMove" (2 members)>
item:  <HDF5 group "/Satya_New/Accelerometer/FloorMove" (8 members)>
item:  <HDF5 group "/Satya_New/Accelerometer/IndoorMove" (1 members)>
item:  <HDF5 group "/Satya_New/Accelerometer/OutdoorMove" (2 members)>
item:  <HDF5 group "/Satya_New/Airquality_pattern" (1 members)>
item:  <HDF5 group "/Satya_New/Airquality_pattern/Unknown" (2 members)>
item:  <HDF5 group "/Satya_New/BCSV" (1 members)>
item:  <HDF5 group "/Satya_New/BCSV/Ball" (8 members)>
item:  <HDF5 group "/Satya_New/California" (1 members)>
item:  <HDF5 group "/Satya_New/California/CO" (110 members)>
item:  <HDF5 group "/Satya_New/Delaware" (1 members)>
item:  <HDF5 group "/Satya_New/Delaware/SO2

In [46]:
datasets.keys()

dict_keys(['Satya_New/Accelerometer', 'Satya_New/Airquality_pattern', 'Satya_New/BCSV', 'Satya_New/California', 'Satya_New/Delaware', 'Satya_New/Florida', 'Satya_New/Gyrometer', 'Satya_New/IBCSV', 'Satya_New/IOCSV', 'Satya_New/Illinois', 'Satya_New/Maryland', 'Satya_New/Michigan', 'Satya_New/NewYork', 'Satya_New/OCSV', 'Satya_New/Texas', 'Satya_New/Wyoming', 'Satya_New/turbofan'])

In [51]:
import pandas as pd
df=pd.read_csv("/data/TimeSeriesResearch/datasets/liu_ice_industrial_fault_diagnosis/trainingdata/wltp_f_pic_090.csv")

In [52]:
df.head()

time  Intercooler_pressure  intercooler_temperature  \
0  0.000000          99976.371765                    299.4   
1  0.050024         100011.047363                    299.4   
2  0.100392          99978.507996                    299.4   
3  0.149982         100001.274109                    299.4   
4  0.200166          99977.363586                    299.4   

   intake_manifold_pressure  air_mass_flow  engine_speed  throttle_position  \
0              33854.923248       0.002900     84.994047           2.614823   
1              31608.995438       0.002726     85.933891           2.508366   
2              31901.941299       0.002565     86.467237           2.259968   
3              29753.658295       0.002396     87.119441           2.118025   
4              28386.569977       0.002300     88.033694           2.118025   

   wastegate_position  injected_fuel_mass  ambient_pressure  \
0            0.622331            0.000624      99985.351562   
1            0.622331            0.000624      99985.351562   
2            0.622331            0.000598      99985.351562   
3            0.622331            0.000598      99985.351562   
4            0.622331            0.000572      99985.351562   

   ambient_temperature  
0           299.087330  
1           299.087330  
2           299.086726  
3           299.086726  
4           299.087885

In [53]:
import pandas as pd
df=pd.read_csv("/data/TimeSeriesResearch/datasets/liu_ice_processed/wltp_f_pic_090.csv")

In [54]:
df.head()

Time  \
0  0.000000   
1  0.050024   
2  0.100392   
3  0.149982   
4  0.200166   

   The sensor measuring the intercooler pressure of a combustion engine.  \
0                                       99976.371765                       
1                                      100011.047363                       
2                                       99978.507996                       
3                                      100001.274109                       
4                                       99977.363586                       

   The sensor measuring intercooler temperature of a combustion engine.  \
0                                              299.4                      
1                                              299.4                      
2                                              299.4                      
3                                              299.4                      
4                                              299.4                      

   The sensor measuring intake manifold pressure of a combustion engine.  \
0                                       33854.923248                       
1                                       31608.995438                       
2                                       31901.941299                       
3                                       29753.658295                       
4                                       28386.569977                       

   The sensor measuring mass flow through the air filter of a combustion engine.  \
0                                           0.002900                               
1                                           0.002726                               
2                                           0.002565                               
3                                           0.002396                               
4                                           0.002300                               

   The sensor measuring rotational engine speed of a combustion engine.  \
0                                          84.994047                      
1                                          85.933891                      
2                                          86.467237                      
3                                          87.119441                      
4                                          88.033694                      

   The sensor measuring throttle actuator position for a vehicle.  \
0                                           2.614823                
1                                           2.508366                
2                                           2.259968                
3                                           2.118025                
4                                           2.118025                

   The actuator value for the requested wastegate actuator position for a combustion engine  \
0                                           0.622331                                          
1                                           0.622331                                          
2                                           0.622331                                          
3                                           0.622331                                          
4                                           0.622331                                          

   The actuator value for the requested injected fuel mass for a combustion engine  \
0                                           0.000624                                 
1                                           0.000624                                 
2                                           0.000598                                 
3                                           0.000598                                 
4                                           0.000572                                 

   The ambient pressure  The ambient temperature  
0          99985.351562               299

In [55]:
df=pd.read_csv("/data/TimeSeriesResearch/datasets/liu_ice_processed_labelled/file_1.csv")

In [56]:
df.head()

Time  \
0  0.000000   
1  0.049996   
2  0.099896   
3  0.150361   
4  0.199847   

   The sensor measuring the intercooler pressure of a combustion engine.  \
0                                       99991.592407                       
1                                       99975.547791                       
2                                       99975.502014                       
3                                       99975.502014                       
4                                       99975.502014                       

   The sensor measuring intercooler temperature of a combustion engine.  \
0                                            298.775                      
1                                            298.775                      
2                                            298.775                      
3                                            298.775                      
4                                            298.775                      

   The sensor measuring intake manifold pressure of a combustion engine.  \
0                                       28581.869125                       
1                                       29656.009674                       
2                                       27703.025818                       
3                                       28288.921356                       
4                                       26726.533890                       

   The sensor measuring mass flow through the air filter of a combustion engine.  \
0                                           0.002484                               
1                                           0.002457                               
2                                           0.002473                               
3                                           0.002489                               
4                                           0.002440                               

   The sensor measuring rotational engine speed of a combustion engine.  \
0                                          89.965423                      
1                                          90.619372                      
2                                          90.868382                      
3                                          92.093029                      
4                                          92.670982                      

   The sensor measuring throttle actuator position for a vehicle.  \
0                                           2.401910                
1                                           2.508366                
2                                           2.508366                
3                                           2.366424                
4                                           2.224482                

   The actuator value for the requested wastegate actuator position for a combustion engine  \
0                                           0.624306                                          
1                                           0.624306                                          
2                                           0.624306                                          
3                                           0.624306                                          
4                                           0.624306                                          

   The actuator value for the requested injected fuel mass for a combustion engine  \
0                                           0.000575                                 
1                                           0.000575                                 
2                                           0.000555                                 
3                                           0.000523                                 
4                                           0.000523                                 

   The ambient pressure  The ambient temperature                 Label  
0          99985.35